### ISSUE TITLE
ToDo List

### ISSUE THREAD

**Issue by REDIZIT** [REDIZIT/FileFlow#1]
## Projects
- [x] Project creation in-app
- [x] Ability to open indexed folders in project via PathBar
- [ ] Run last build
- [ ] Useful urls (Google Drive, Yandex Disk, GitHub and etc)

Think about:
- Start/Restart button for all tools, like Unity, Visual Studio, GitHub
- Unity Editor sync (object ping after fast-download file moved)

## Search
- [ ] Ability to exclude system folders and files
- [ ] Search by files content, maybe with matches preview
- [ ] Better sort algorithm at FilesView: first of all goes full matches, then less matching
- [ ] Saving results (to allow history and tabs switching without researching)

## Context menu
- [ ] Deleting file which is used by another process
- [ ] Ability to change file name (also after fast-download) when user is moving a couple of files (not like in Windows)
- [x] Ability to open cmd in current folder
- [x] Copy file path
- [ ] Add file to programs (To make visible for FluentSearch)

## Archive
- [x] Viewing archive like a folder
- [x] Archive creation
- [ ] Password support
- [ ] .zip, .rar support

## Explorer
- [x] PathBar index common used folders (Roaming, Users and etc)
- [x] Drag and drop
- [x] Display new file indicator, to fast figure out which files have been created or changed
- [ ] Integrated YandexDisk and may be GoogleDrive
- [x] Ctrl+D - duplicate file

Think about:
- Sync with mobile phone, like buffer and files transfer
